//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.f.resource_injection;

<<<<<<< HEAD
import android.R.anim;
import android.content.Context;
import android.content.res.Resources;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.view.animation.AnimationUtils;
import com.kent.androidannotationsdemo.R.color;
import com.kent.androidannotationsdemo.R.dimen;
import com.kent.androidannotationsdemo.R.string;
=======
import android.content.Context;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
>>>>>>> 26f0af6cd8875d78402923498af61e9c7ff49cbe
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class FActy_
    extends FActy
    implements HasViews
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    private void init_(Bundle savedInstanceState) {
<<<<<<< HEAD
        Resources resources_ = this.getResources();
        stringInject = resources_.getString(string.string_inject);
        xmlResAnim1 = AnimationUtils.loadAnimation(this, anim.fade_in);
        xmlResAnim0 = resources_.getAnimation(anim.fade_in);
        fontSize = resources_.getDimension(dimen.font_size);
        colorInject = resources_.getColor(color.color_inject);
=======
>>>>>>> 26f0af6cd8875d78402923498af61e9c7ff49cbe
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static FActy_.IntentBuilder_ intent(Context context) {
        return new FActy_.IntentBuilder_(context);
    }

    public static FActy_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new FActy_.IntentBuilder_(fragment);
    }

    public static FActy_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new FActy_.IntentBuilder_(supportFragment);
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<FActy_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, FActy_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), FActy_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), FActy_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

    }

}
