//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.2.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.h.typesafe_sharedpreferences;

import android.content.Context;
import android.content.SharedPreferences;
import com.kent.androidannotationsdemo.R.string;
import org.androidannotations.api.sharedpreferences.EditorHelper;
import org.androidannotations.api.sharedpreferences.IntPrefEditorField;
import org.androidannotations.api.sharedpreferences.IntPrefField;
import org.androidannotations.api.sharedpreferences.LongPrefEditorField;
import org.androidannotations.api.sharedpreferences.LongPrefField;
import org.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import org.androidannotations.api.sharedpreferences.StringPrefEditorField;
import org.androidannotations.api.sharedpreferences.StringPrefField;

public final class ActivityPrefs_
    extends SharedPreferencesHelper
{

    private Context context_;

    public ActivityPrefs_(Context context) {
        super(context.getSharedPreferences((getLocalClassName(context)+"_ActivityPrefs"), 0));
        this.context_ = context;
    }

    public ActivityPrefs_.ActivityPrefsEditor_ edit() {
        return new ActivityPrefs_.ActivityPrefsEditor_(getSharedPreferences());
    }

    private static String getLocalClassName(Context context) {
        String packageName = context.getPackageName();
        String className = context.getClass().getName();
        int packageLen = packageName.length();
        if (((!className.startsWith(packageName))||(className.length()<= packageLen))||(className.charAt(packageLen)!= '.')) {
            return className;
        }
        return className.substring((packageLen + 1));
    }

    public IntPrefField age() {
        return intField("age", 20);
    }

    public LongPrefField lastUpdate() {
        return longField("lastUpdate", 0L);
    }

    public StringPrefField name() {
        return stringField("name", "John");
    }

    public StringPrefField resourceName() {
        return stringField("resourceName", context_.getResources().getString(string.nick_name));
    }

    public StringPrefField scopeName() {
        return stringField("scopeName", "DefaultName");
    }

    public final static class ActivityPrefsEditor_
        extends EditorHelper<ActivityPrefs_.ActivityPrefsEditor_>
    {


        ActivityPrefsEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public IntPrefEditorField<ActivityPrefs_.ActivityPrefsEditor_> age() {
            return intField("age");
        }

        public LongPrefEditorField<ActivityPrefs_.ActivityPrefsEditor_> lastUpdate() {
            return longField("lastUpdate");
        }

        public StringPrefEditorField<ActivityPrefs_.ActivityPrefsEditor_> name() {
            return stringField("name");
        }

        public StringPrefEditorField<ActivityPrefs_.ActivityPrefsEditor_> resourceName() {
            return stringField("resourceName");
        }

        public StringPrefEditorField<ActivityPrefs_.ActivityPrefsEditor_> scopeName() {
            return stringField("scopeName");
        }

    }

}
