//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.2.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.h.typesafe_sharedpreferences;

import android.content.Context;
import android.content.SharedPreferences;
import android.preference.PreferenceManager;
import com.kent.androidannotationsdemo.R.string;
import org.androidannotations.api.sharedpreferences.EditorHelper;
import org.androidannotations.api.sharedpreferences.IntPrefEditorField;
import org.androidannotations.api.sharedpreferences.IntPrefField;
import org.androidannotations.api.sharedpreferences.LongPrefEditorField;
import org.androidannotations.api.sharedpreferences.LongPrefField;
import org.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import org.androidannotations.api.sharedpreferences.StringPrefEditorField;
import org.androidannotations.api.sharedpreferences.StringPrefField;

public final class ApplicationPrefs_
    extends SharedPreferencesHelper
{

    private Context context_;

    public ApplicationPrefs_(Context context) {
        super(PreferenceManager.getDefaultSharedPreferences(context));
        this.context_ = context;
    }

    public ApplicationPrefs_.ApplicationPrefsEditor_ edit() {
        return new ApplicationPrefs_.ApplicationPrefsEditor_(getSharedPreferences());
    }

    public IntPrefField age() {
        return intField("age", 20);
    }

    public LongPrefField lastUpdate() {
        return longField("lastUpdate", 0L);
    }

    public StringPrefField name() {
        return stringField("name", "John");
    }

    public StringPrefField resourceName() {
        return stringField("resourceName", context_.getResources().getString(string.nick_name));
    }

    public StringPrefField scopeName() {
        return stringField("scopeName", "DefaultName");
    }

    public final static class ApplicationPrefsEditor_
        extends EditorHelper<ApplicationPrefs_.ApplicationPrefsEditor_>
    {


        ApplicationPrefsEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public IntPrefEditorField<ApplicationPrefs_.ApplicationPrefsEditor_> age() {
            return intField("age");
        }

        public LongPrefEditorField<ApplicationPrefs_.ApplicationPrefsEditor_> lastUpdate() {
            return longField("lastUpdate");
        }

        public StringPrefEditorField<ApplicationPrefs_.ApplicationPrefsEditor_> name() {
            return stringField("name");
        }

        public StringPrefEditorField<ApplicationPrefs_.ApplicationPrefsEditor_> resourceName() {
            return stringField("resourceName");
        }

        public StringPrefEditorField<ApplicationPrefs_.ApplicationPrefsEditor_> scopeName() {
            return stringField("scopeName");
        }

    }

}
