//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.h.typesafe_sharedpreferences;

import android.content.Context;
import android.os.Bundle;
import android.view.View;
<<<<<<< HEAD
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.TextView;
import com.kent.androidannotationsdemo.R.id;
import com.kent.androidannotationsdemo.R.layout;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class HActy_
    extends com.h.typesafe_sharedpreferences.HActy
    implements HasViews, OnViewChangedListener
=======
import android.view.ViewGroup.LayoutParams;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class HActy_
    extends HActy
    implements HasViews
>>>>>>> 26f0af6cd8875d78402923498af61e9c7ff49cbe
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
<<<<<<< HEAD
        setContentView(layout.hacty_layout);
    }

    private void init_(Bundle savedInstanceState) {
        myPrefs = new MyPrefInterface_(this);
        MyPrefs = new MyPrefInterface_(this);
        HActy_MyPrefs = new MyPrefInterface_(this);
        HActy = new MyPrefInterface_(this);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
=======
    }

    private void init_(Bundle savedInstanceState) {
>>>>>>> 26f0af6cd8875d78402923498af61e9c7ff49cbe
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static HActy_.IntentBuilder_ intent(Context context) {
        return new HActy_.IntentBuilder_(context);
    }

    public static HActy_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new HActy_.IntentBuilder_(fragment);
    }

    public static HActy_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new HActy_.IntentBuilder_(supportFragment);
    }

<<<<<<< HEAD
    @Override
    public void onViewChanged(HasViews hasViews) {
        h_ed_name = ((TextView) hasViews.findViewById(id.h_ed_name));
        h_tv_age = ((TextView) hasViews.findViewById(id.h_tv_age));
        h_tv_name = ((TextView) hasViews.findViewById(id.h_tv_name));
        h_ed_age = ((TextView) hasViews.findViewById(id.h_ed_age));
        h_tv_prefsStatus = ((TextView) hasViews.findViewById(id.h_tv_prefsStatus));
        {
            View view = hasViews.findViewById(id.h_btn_name);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HActy_.this.onclick(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.h_btn_age);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HActy_.this.onclick(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.h_btn_clear);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HActy_.this.onclick(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.h_btn_prefsStatus);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HActy_.this.onclick(view);
                    }

                }
                );
            }
        }
    }

=======
>>>>>>> 26f0af6cd8875d78402923498af61e9c7ff49cbe
    public static class IntentBuilder_
        extends ActivityIntentBuilder<HActy_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, HActy_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), HActy_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), HActy_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

    }

}
