//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.2.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.h.typesafe_sharedpreferences;

import android.app.Activity;
import android.content.Context;
import android.os.Build.VERSION;
import android.os.Build.VERSION_CODES;
import android.os.Bundle;
import android.support.v4.app.ActivityCompat;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.EditText;
import android.widget.TextView;
import com.kent.androidannotationsdemo.R.id;
import com.kent.androidannotationsdemo.R.layout;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class HActy_
    extends HActy
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.hacty_layout);
    }

    private void init_(Bundle savedInstanceState) {
        applicationPrefs = new ApplicationPrefs_(this);
        activityPrefs = new ActivityPrefs_(this);
        defaultPrefs = new DefaultPrefs_(this);
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static HActy_.IntentBuilder_ intent(Context context) {
        return new HActy_.IntentBuilder_(context);
    }

    public static HActy_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new HActy_.IntentBuilder_(fragment);
    }

    public static HActy_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new HActy_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        h_tv_age = ((TextView) hasViews.findViewById(id.h_tv_age));
        h_ed_name = ((TextView) hasViews.findViewById(id.h_ed_name));
        edScopeName = ((EditText) hasViews.findViewById(id.h_ed_scopeName));
        h_ed_age = ((TextView) hasViews.findViewById(id.h_ed_age));
        h_tv_prefsStatus = ((TextView) hasViews.findViewById(id.h_tv_prefsStatus));
        tvScopeName = ((TextView) hasViews.findViewById(id.h_tv_scopeName));
        h_tv_name = ((TextView) hasViews.findViewById(id.h_tv_name));
        {
            View view = hasViews.findViewById(id.h_btn_name);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HActy_.this.onclick(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.h_btn_age);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HActy_.this.onclick(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.h_btn_clear);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HActy_.this.onclick(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.h_btn_prefsStatus);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HActy_.this.onclick(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.h_btn_secActy);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HActy_.this.onclick(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.h_btn_actyPrefs);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HActy_.this.onclick(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.h_btn_defaultPrefs);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HActy_.this.onclick(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.h_btn_applicationPrefs);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HActy_.this.onclick(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.h_btn_prefsActy);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        HActy_.this.onclick(view);
                    }

                }
                );
            }
        }
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<HActy_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, HActy_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), HActy_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), HActy_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    if (VERSION.SDK_INT >= VERSION_CODES.JELLY_BEAN) {
                        fragment_.startActivityForResult(intent, requestCode, lastOptions);
                    } else {
                        fragment_.startActivityForResult(intent, requestCode);
                    }
                } else {
                    if (context instanceof Activity) {
                        Activity activity = ((Activity) context);
                        ActivityCompat.startActivityForResult(activity, intent, requestCode, lastOptions);
                    } else {
                        if (VERSION.SDK_INT >= VERSION_CODES.JELLY_BEAN) {
                            context.startActivity(intent, lastOptions);
                        } else {
                            context.startActivity(intent);
                        }
                    }
                }
            }
        }

    }

}
