//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.2.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.h.typesafe_sharedpreferences;

import android.app.Activity;
import android.content.Context;
import android.os.Build.VERSION;
import android.os.Build.VERSION_CODES;
import android.os.Bundle;
import android.preference.CheckBoxPreference;
import android.preference.Preference;
import android.preference.Preference.OnPreferenceChangeListener;
import android.preference.Preference.OnPreferenceClickListener;
import android.support.v4.app.ActivityCompat;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import com.kent.androidannotationsdemo.R.string;
import com.kent.androidannotationsdemo.R.xml;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class HSharePrefreferenceActy_
    extends HSharePrefreferenceActy
    implements HasViews
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        addPreferencesFromResource(xml.preference);
    }

    private void init_(Bundle savedInstanceState) {
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static HSharePrefreferenceActy_.IntentBuilder_ intent(Context context) {
        return new HSharePrefreferenceActy_.IntentBuilder_(context);
    }

    public static HSharePrefreferenceActy_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new HSharePrefreferenceActy_.IntentBuilder_(fragment);
    }

    public static HSharePrefreferenceActy_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new HSharePrefreferenceActy_.IntentBuilder_(supportFragment);
    }

    @Override
    public void addPreferencesFromResource(int preferencesResId) {
        super.addPreferencesFromResource(preferencesResId);
        threeGCheckBox = ((CheckBoxPreference) this.findPreference(this.getString(string.set_3g)));
        RovingCheckBox = ((CheckBoxPreference) this.findPreference(this.getString(string.set_roving)));
        if (threeGCheckBox!= null) {
            threeGCheckBox.setOnPreferenceChangeListener(new OnPreferenceChangeListener() {


                @Override
                public boolean onPreferenceChange(Preference preference, Object newValue) {
                    HSharePrefreferenceActy_.this.checkedChangedOn3G(preference);
                    return true;
                }

            }
            );
        }
        if (RovingCheckBox!= null) {
            RovingCheckBox.setOnPreferenceClickListener(new OnPreferenceClickListener() {


                @Override
                public boolean onPreferenceClick(Preference preference) {
                    HSharePrefreferenceActy_.this.onRovingClick();
                    return true;
                }

            }
            );
        }
        afterPrefs();
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<HSharePrefreferenceActy_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, HSharePrefreferenceActy_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), HSharePrefreferenceActy_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), HSharePrefreferenceActy_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    if (VERSION.SDK_INT >= VERSION_CODES.JELLY_BEAN) {
                        fragment_.startActivityForResult(intent, requestCode, lastOptions);
                    } else {
                        fragment_.startActivityForResult(intent, requestCode);
                    }
                } else {
                    if (context instanceof Activity) {
                        Activity activity = ((Activity) context);
                        ActivityCompat.startActivityForResult(activity, intent, requestCode, lastOptions);
                    } else {
                        if (VERSION.SDK_INT >= VERSION_CODES.JELLY_BEAN) {
                            context.startActivity(intent, lastOptions);
                        } else {
                            context.startActivity(intent);
                        }
                    }
                }
            }
        }

    }

}
