//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.h.typesafe_sharedpreferences;

import android.content.Context;
import android.content.SharedPreferences;
import com.kent.androidannotationsdemo.R.string;
import org.androidannotations.api.sharedpreferences.EditorHelper;
import org.androidannotations.api.sharedpreferences.IntPrefEditorField;
import org.androidannotations.api.sharedpreferences.IntPrefField;
import org.androidannotations.api.sharedpreferences.LongPrefEditorField;
import org.androidannotations.api.sharedpreferences.LongPrefField;
import org.androidannotations.api.sharedpreferences.SharedPreferencesHelper;
import org.androidannotations.api.sharedpreferences.StringPrefEditorField;
import org.androidannotations.api.sharedpreferences.StringPrefField;

public final class MyPrefInterface_
    extends SharedPreferencesHelper
{

    private Context context_;

    public MyPrefInterface_(Context context) {
        super(context.getSharedPreferences((getLocalClassName(context)+"_MyPrefInterface"), 0));
        this.context_ = context;
    }

    public MyPrefInterface_.MyPrefInterfaceEditor_ edit() {
        return new MyPrefInterface_.MyPrefInterfaceEditor_(getSharedPreferences());
    }

    private static String getLocalClassName(Context context) {
        String packageName = context.getPackageName();
        String className = context.getClass().getName();
        int packageLen = packageName.length();
        if (((!className.startsWith(packageName))||(className.length()<= packageLen))||(className.charAt(packageLen)!= '.')) {
            return className;
        }
        return className.substring((packageLen + 1));
    }

    public IntPrefField age() {
        return intField("age", 20);
    }

    public LongPrefField lastUpdate() {
        return longField("lastUpdate", 0L);
    }

    public StringPrefField name() {
        return stringField("name", "John");
    }

    public StringPrefField resourceName() {
        return stringField("resourceName", context_.getResources().getString(string.nick_name));
    }

    public final static class MyPrefInterfaceEditor_
        extends EditorHelper<MyPrefInterface_.MyPrefInterfaceEditor_>
    {


        MyPrefInterfaceEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public IntPrefEditorField<MyPrefInterface_.MyPrefInterfaceEditor_> age() {
            return intField("age");
        }

        public LongPrefEditorField<MyPrefInterface_.MyPrefInterfaceEditor_> lastUpdate() {
            return longField("lastUpdate");
        }

        public StringPrefEditorField<MyPrefInterface_.MyPrefInterfaceEditor_> name() {
            return stringField("name");
        }

        public StringPrefEditorField<MyPrefInterface_.MyPrefInterfaceEditor_> resourceName() {
            return stringField("resourceName");
        }

    }

}
