//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.2.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.e.misc;

import android.app.Activity;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.database.sqlite.SQLiteDatabase;
import android.os.Build.VERSION;
import android.os.Build.VERSION_CODES;
import android.os.Bundle;
import android.support.v4.app.ActivityCompat;
import android.util.Log;
import android.view.View;
import android.view.View.OnClickListener;
import android.widget.EditText;
import android.widget.TextView;
import com.kent.androidannotationsdemo.R.id;
import com.kent.androidannotationsdemo.R.layout;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class EActy_
    extends EActy
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private final IntentFilter intentFilter1_ = new IntentFilter();
    private final BroadcastReceiver onActionReceiver_ = new BroadcastReceiver() {

        public final static String NAME_EXTRA = "name";
        public final static String AGE_EXTRA = "age";

        public void onReceive(Context context, Intent intent) {
            Bundle extras_ = ((intent.getExtras()!= null)?intent.getExtras():new Bundle());
            String name = extras_.getString(NAME_EXTRA);
            int ageFromIntent = extras_.getInt(AGE_EXTRA);
            EActy_.this.onAction(name, ageFromIntent, context);
        }

    }
    ;
    public final static String NAME_EXTRA = "name";
    public final static String AGE_EXTRA = "age";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.eacty_layout);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        getWindow().setFlags(android.view.WindowManager.LayoutParams.FLAG_FULLSCREEN, android.view.WindowManager.LayoutParams.FLAG_FULLSCREEN);
        restoreSavedInstanceState_(savedInstanceState);
        requestWindowFeature(1);
        requestWindowFeature(5);
        intentFilter1_.addAction("com.kent.sendBroadcast");
        this.registerReceiver(onActionReceiver_, intentFilter1_);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, android.view.ViewGroup.LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static EActy_.IntentBuilder_ intent(Context context) {
        return new EActy_.IntentBuilder_(context);
    }

    public static EActy_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new EActy_.IntentBuilder_(fragment);
    }

    public static EActy_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new EActy_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        nameTv = ((TextView) hasViews.findViewById(id.e_tv_name));
        nameEd = ((EditText) hasViews.findViewById(id.e_ed_name));
        {
            View view = hasViews.findViewById(id.e_orientation);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        EActy_.this.onCLick(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.e_btn_name);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        EActy_.this.onCLick(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.e_btn_forResult);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        EActy_.this.onCLick(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.e_btn_sendBroadcast);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        EActy_.this.onCLick(view);
                    }

                }
                );
            }
        }
        afterViews();
    }

    @Override
    public void doSomeDbWork(final SQLiteDatabase db) {
        db.beginTransaction();
        try {
            EActy_.super.doSomeDbWork(db);
            db.setTransactionSuccessful();
            return ;
        } catch (RuntimeException e) {
            Log.e("EActy_", "Error in transaction", e);
            throw e;
        } finally {
            db.endTransaction();
        }
    }

    @Override
    public void onSaveInstanceState(Bundle bundle_) {
        super.onSaveInstanceState(bundle_);
        bundle_.putString("name", name);
    }

    private void restoreSavedInstanceState_(Bundle savedInstanceState) {
        if (savedInstanceState == null) {
            return ;
        }
        name = savedInstanceState.getString("name");
    }

    @Override
    public void onDestroy() {
        this.unregisterReceiver(onActionReceiver_);
        super.onDestroy();
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        switch (requestCode) {
            case  0 :
                {
                    Bundle extras_ = (((data!= null)&&(data.getExtras()!= null))?data.getExtras():new Bundle());
                    String name = extras_.getString(NAME_EXTRA);
                    String age = extras_.getString(AGE_EXTRA);
                    EActy_.this.onResule(resultCode, data, name, age);
                }
                EActy_.this.onResult(resultCode, data);
                break;
        }
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<EActy_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, EActy_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), EActy_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), EActy_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    if (VERSION.SDK_INT >= VERSION_CODES.JELLY_BEAN) {
                        fragment_.startActivityForResult(intent, requestCode, lastOptions);
                    } else {
                        fragment_.startActivityForResult(intent, requestCode);
                    }
                } else {
                    if (context instanceof Activity) {
                        Activity activity = ((Activity) context);
                        ActivityCompat.startActivityForResult(activity, intent, requestCode, lastOptions);
                    } else {
                        if (VERSION.SDK_INT >= VERSION_CODES.JELLY_BEAN) {
                            context.startActivity(intent, lastOptions);
                        } else {
                            context.startActivity(intent);
                        }
                    }
                }
            }
        }

    }

}
