//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.e.misc;

<<<<<<< HEAD
import java.util.Arrays;
import java.util.List;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
=======
>>>>>>> 26f0af6cd8875d78402923498af61e9c7ff49cbe

public final class EMyReceiver_
    extends EMyReceiver
{

<<<<<<< HEAD
    public final static String ACTION_MY_SIMPLE_ACTION = "MySimpleBroadcase";
    private Context context_;
    public final static String ACTION_ON_HTTPS = "heheBroadcast";
    public final static List<String> DATA_SCHEMES_ON_HTTPS = Arrays.asList("http", "https");
    public final static String ACTION_ANOTHER_ACTION = "anotherAction";
    public final static String SPECIAL_EXTRA_NAME_EXTRA = "specialExtraName";
    public final static String VALUE_LONG_EXTRA = "valueLong";
    public final static String ACTION_ON_HTTP = "heheBroadcast";
    public final static List<String> DATA_SCHEMES_ON_HTTP = Arrays.asList("http");

    @Override
    public void onReceive(Context context, Intent intent) {
        context_ = context;
        init_();
        super.onReceive(context, intent);
        String action = intent.getAction();
        String dataScheme = intent.getScheme();
        if (ACTION_MY_SIMPLE_ACTION.equals(action)) {
            EMyReceiver_.this.mySimpleAction(intent);
            return ;
        }
        if (ACTION_ON_HTTPS.equals(action)&&DATA_SCHEMES_ON_HTTPS.contains(dataScheme)) {
            EMyReceiver_.this.onHttps();
            return ;
        }
        if (ACTION_ANOTHER_ACTION.equals(action)) {
            Bundle extras_ = ((intent.getExtras()!= null)?intent.getExtras():new Bundle());
            String valueString = extras_.getString(SPECIAL_EXTRA_NAME_EXTRA);
            long valueLong = extras_.getLong(VALUE_LONG_EXTRA);
            EMyReceiver_.this.anotherAction(valueString, valueLong);
            return ;
        }
        if (ACTION_ON_HTTP.equals(action)&&DATA_SCHEMES_ON_HTTP.contains(dataScheme)) {
            EMyReceiver_.this.onHttp();
            return ;
        }
    }

    private void init_() {
    }
=======
>>>>>>> 26f0af6cd8875d78402923498af61e9c7ff49cbe

}
