//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.2.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.e.misc;

import java.util.Arrays;
import java.util.List;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;

public final class EMyReceiver_
    extends EMyReceiver
{

    public final static String ACTIONS_ON_HTTPS = "heheBroadcast";
    public final static List<String> DATA_SCHEMES_ON_HTTPS = Arrays.asList("http", "https");
    public final static String ACTIONS_MY_SIMPLE_ACTION = "MySimpleBroadcase";
    public final static String ACTIONS_ANOTHER_ACTION = "anotherAction";
    public final static String SPECIAL_EXTRA_NAME_EXTRA = "specialExtraName";
    public final static String VALUE_LONG_EXTRA = "valueLong";
    public final static String ACTIONS_ON_HTTP = "heheBroadcast";
    public final static String DATA_SCHEMES_ON_HTTP = "http";

    @Override
    public void onReceive(Context context, Intent intent) {
        init_(context);
        super.onReceive(context, intent);
        String action = intent.getAction();
        String dataScheme = intent.getScheme();
        if (ACTIONS_ON_HTTPS.equals(action)&&DATA_SCHEMES_ON_HTTPS.contains(dataScheme)) {
            EMyReceiver_.this.onHttps();
            return ;
        }
        if (ACTIONS_MY_SIMPLE_ACTION.equals(action)) {
            EMyReceiver_.this.mySimpleAction(intent);
            return ;
        }
        if (ACTIONS_ANOTHER_ACTION.equals(action)) {
            Bundle extras_ = ((intent.getExtras()!= null)?intent.getExtras():new Bundle());
            String valueString = extras_.getString(SPECIAL_EXTRA_NAME_EXTRA);
            long valueLong = extras_.getLong(VALUE_LONG_EXTRA);
            EMyReceiver_.this.anotherAction(valueString, valueLong);
            return ;
        }
        if (ACTIONS_ON_HTTP.equals(action)&&DATA_SCHEMES_ON_HTTP.equals(dataScheme)) {
            EMyReceiver_.this.onHttp();
            return ;
        }
    }

    private void init_(Context context) {
    }

}
