//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.a.enhanced_components;

import android.content.Context;

public final class MyBean_
    extends MyBean
{

    private Context context_;

    private MyBean_(Context context) {
        context_ = context;
        init_();
    }

    public static MyBean_ getInstance_(Context context) {
        return new MyBean_(context);
    }

    private void init_() {
        afterInject();
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
