//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.2.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.a.enhanced_components;

import android.content.Context;
import org.androidannotations.api.builder.ServiceIntentBuilder;

public final class MyIntentService_
    extends MyIntentService
{


    public static MyIntentService_.IntentBuilder_ intent(Context context) {
        return new MyIntentService_.IntentBuilder_(context);
    }

    public static class IntentBuilder_
        extends ServiceIntentBuilder<MyIntentService_.IntentBuilder_>
    {


        public IntentBuilder_(Context context) {
            super(context, MyIntentService_.class);
        }

    }

}
