//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.a.enhanced_components;

import org.androidannotations.api.builder.ServiceIntentBuilder;

import android.content.Context;

public final class MyIntentService_
    extends MyIntentService
{


    public static MyIntentService_.IntentBuilder_ intent(Context context) {
        return new MyIntentService_.IntentBuilder_(context);
    }

    public static class IntentBuilder_
        extends ServiceIntentBuilder<MyIntentService_.IntentBuilder_>
    {


        public IntentBuilder_(Context context) {
            super(context, MyIntentService_.class);
        }

    }

}
