//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.2.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.a.enhanced_components;


public final class MyProvider_
    extends MyProvider
{


    private void init_() {
        injected();
    }

    @Override
    public boolean onCreate() {
        init_();
        return super.onCreate();
    }

}
