//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.a.enhanced_components;


public final class MyProvider_
    extends MyProvider
{


    private void init_() {
        injected();
    }

    @Override
    public boolean onCreate() {
        init_();
        return super.onCreate();
    }

}
