//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.2.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.a.enhanced_components;


public final class MyReceiver_
    extends MyReceiver
{


}
