//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.a.enhanced_components;

import org.androidannotations.api.builder.ServiceIntentBuilder;

import android.content.Context;

public final class MyService_
    extends MyService
{


    public static MyService_.IntentBuilder_ intent(Context context) {
        return new MyService_.IntentBuilder_(context);
    }

    public static class IntentBuilder_
        extends ServiceIntentBuilder<MyService_.IntentBuilder_>
    {


        public IntentBuilder_(Context context) {
            super(context, MyService_.class);
        }

    }

}
