//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.a.enhanced_components;

import org.androidannotations.api.view.OnViewChangedNotifier;

import android.content.Context;

public final class SingletonBean_
    extends SingletonBean
{

    private Context context_;
    private static SingletonBean_ instance_;

    private SingletonBean_(Context context) {
        context_ = context;
    }

    public static SingletonBean_ getInstance_(Context context) {
        if (instance_ == null) {
            OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(null);
            instance_ = new SingletonBean_(context.getApplicationContext());
            instance_.init_();
            OnViewChangedNotifier.replaceNotifier(previousNotifier);
        }
        return instance_;
    }

    private void init_() {
        injected();
    }

}
