//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.c.event_binding;

import android.content.Context;
import android.os.Bundle;
import android.text.Editable;
import android.text.TextWatcher;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.View.OnFocusChangeListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.CompoundButton;
import android.widget.CompoundButton.OnCheckedChangeListener;
import android.widget.EditText;
import android.widget.SeekBar;
import android.widget.SeekBar.OnSeekBarChangeListener;
import android.widget.TextView;
import com.kent.androidannotationsdemo.R.id;
import com.kent.androidannotationsdemo.R.layout;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class CActy_
    extends CActy
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.cacty_layout);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static CActy_.IntentBuilder_ intent(Context context) {
        return new CActy_.IntentBuilder_(context);
    }

    public static CActy_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new CActy_.IntentBuilder_(fragment);
    }

    public static CActy_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new CActy_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        edTv = ((EditText) hasViews.findViewById(id.c_edTv));
        seekBarTv = ((TextView) hasViews.findViewById(id.c_seekBar_tv));
        infoTv = ((TextView) hasViews.findViewById(id.c_tv_showInfo));
        seekBarStatus = ((TextView) hasViews.findViewById(id.c_seekBar_status));
        tv = ((TextView) hasViews.findViewById(id.c_tv));
        {
            View view = hasViews.findViewById(id.c_btn_submit);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        CActy_.this.onClick(view);
                    }

                }
                );
            }
        }
        {
            View view = hasViews.findViewById(id.c_btn_listViewActy);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        CActy_.this.onClick(view);
                    }

                }
                );
            }
        }
        if (edTv!= null) {
            edTv.setOnFocusChangeListener(new OnFocusChangeListener() {


                @Override
                public void onFocusChange(View view, boolean hasFocus) {
                    CActy_.this.edTvFocusChange(view, hasFocus);
                }

            }
            );
        }
        {
            CompoundButton view = ((CompoundButton) hasViews.findViewById(id.c_theckBox));
            if (view!= null) {
                view.setOnCheckedChangeListener(new OnCheckedChangeListener() {


                    @Override
                    public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                        CActy_.this.onCheckChange(buttonView, isChecked);
                    }

                }
                );
            }
        }
        {
            CompoundButton view = ((CompoundButton) hasViews.findViewById(id.c_radio0));
            if (view!= null) {
                view.setOnCheckedChangeListener(new OnCheckedChangeListener() {


                    @Override
                    public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                        CActy_.this.checked(buttonView, isChecked);
                    }

                }
                );
            }
        }
        {
            CompoundButton view = ((CompoundButton) hasViews.findViewById(id.c_radio1));
            if (view!= null) {
                view.setOnCheckedChangeListener(new OnCheckedChangeListener() {


                    @Override
                    public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                        CActy_.this.checked(buttonView, isChecked);
                    }

                }
                );
            }
        }
        {
            CompoundButton view = ((CompoundButton) hasViews.findViewById(id.c_radio2));
            if (view!= null) {
                view.setOnCheckedChangeListener(new OnCheckedChangeListener() {


                    @Override
                    public void onCheckedChanged(CompoundButton buttonView, boolean isChecked) {
                        CActy_.this.checked(buttonView, isChecked);
                    }

                }
                );
            }
        }
        {
            final TextView view = ((TextView) hasViews.findViewById(id.c_tv));
            if (view!= null) {
                view.addTextChangedListener(new TextWatcher() {


                    @Override
                    public void beforeTextChanged(CharSequence s, int start, int count, int after) {
                        CActy_.this.beforeTextChange(view, s, start, count, after);
                    }

                    @Override
                    public void onTextChanged(CharSequence s, int start, int before, int count) {
                        CActy_.this.onTvTextChange(s, view, before, start, count);
                        CActy_.this.c_TvTextChanged();
                        CActy_.this.textChange();
                        CActy_.this.ctvTextChange();
                    }

                    @Override
                    public void afterTextChanged(Editable s) {
                        CActy_.this.afterTextChange(s, view);
                    }

                }
                );
            }
        }
        {
            final TextView view = ((TextView) hasViews.findViewById(id.c_edTv));
            if (view!= null) {
                view.addTextChangedListener(new TextWatcher() {


                    @Override
                    public void beforeTextChanged(CharSequence s, int start, int count, int after) {
                    }

                    @Override
                    public void onTextChanged(CharSequence s, int start, int before, int count) {
                        CActy_.this.textChange();
                    }

                    @Override
                    public void afterTextChanged(Editable s) {
                    }

                }
                );
            }
        }
        {
            final SeekBar view = ((SeekBar) hasViews.findViewById(id.c_seekBar));
            if (view!= null) {
                view.setOnSeekBarChangeListener(new OnSeekBarChangeListener() {


                    @Override
                    public void onProgressChanged(SeekBar seekBar, int progress, boolean fromUser) {
                        CActy_.this.onProgressChange(seekBar, progress, fromUser);
                    }

                    @Override
                    public void onStartTrackingTouch(SeekBar seekBar) {
                        CActy_.this.touchStart();
                    }

                    @Override
                    public void onStopTrackingTouch(SeekBar seekBar) {
                        CActy_.this.touchStop();
                    }

                }
                );
            }
        }
        afterViews();
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        MenuInflater menuInflater = getMenuInflater();
        menuInflater.inflate(com.kent.androidannotationsdemo.R.menu.main, menu);
        menuItem = menu.findItem(id.action_settings3);
        return super.onCreateOptionsMenu(menu);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        boolean handled = super.onOptionsItemSelected(item);
        if (handled) {
            return true;
        }
        int itemId_ = item.getItemId();
        if (itemId_ == id.action_settings2) {
            action_settings2Selected(item);
            return true;
        }
        if (((itemId_ == id.action_settings3)||(itemId_ == id.action_settings4))||(itemId_ == id.action_settings5)) {
            optionSelected(item);
            return true;
        }
        if (itemId_ == id.action_settings1) {
            optionItem1();
            return true;
        }
        return false;
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<CActy_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, CActy_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), CActy_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), CActy_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

    }

}
