//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.b.injection;

import android.content.Context;
import android.content.Intent;
import android.content.res.Resources;
import android.os.Bundle;
import android.text.Html;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.TextView;
import com.kent.androidannotationsdemo.R.id;
import com.kent.androidannotationsdemo.R.layout;
import com.kent.androidannotationsdemo.R.string;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class BActy_
    extends BActy
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String NAME_EXTRA = "name";
    public final static String AGE_EXTRA = "age";

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.bacty_layout);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        Resources resources_ = this.getResources();
        hello_Html = Html.fromHtml(resources_.getString(string.hello_html));
        myHelloString = Html.fromHtml(resources_.getString(string.hello_html));
        hello_html = Html.fromHtml(resources_.getString(string.hello_html));
        injectExtras_();
        afterInject();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static BActy_.IntentBuilder_ intent(Context context) {
        return new BActy_.IntentBuilder_(context);
    }

    public static BActy_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new BActy_.IntentBuilder_(fragment);
    }

    public static BActy_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new BActy_.IntentBuilder_(supportFragment);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        mTextView = ((TextView) hasViews.findViewById(id.b_commom_tv));
        htmlRes = ((TextView) hasViews.findViewById(id.b_htmlRes));
        helloHtml = ((TextView) hasViews.findViewById(id.b_fromHtml));
        if (helloHtml!= null) {
            helloHtml.setText(Html.fromHtml(this.getString(string.hello_html)));
        }
        afterViews();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(NAME_EXTRA)) {
                name = extras_.getString(NAME_EXTRA);
            }
            if (extras_.containsKey(AGE_EXTRA)) {
                age = extras_.getInt(AGE_EXTRA);
            }
            afterExtras();
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    @Override
    public void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        setIntent(intent);
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<BActy_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, BActy_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), BActy_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), BActy_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

        public BActy_.IntentBuilder_ name(String name) {
            return super.extra(NAME_EXTRA, name);
        }

        public BActy_.IntentBuilder_ age(int age) {
            return super.extra(AGE_EXTRA, age);
        }

    }

}
