//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.b.injection;

import android.content.Context;

public final class MyEBean_
    extends MyEBean
{

    private Context context_;

    private MyEBean_(Context context) {
        context_ = context;
        init_();
    }

    public static MyEBean_ getInstance_(Context context) {
        return new MyEBean_(context);
    }

    private void init_() {
        afterInject();
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
