//
// DO NOT EDIT THIS FILE.Generated using AndroidAnnotations 3.3.2.
//  You can create a larger work that contains this file and distribute that work under terms of your choice.
//


package com.b.injection;

import android.content.Context;

public final class MyEBean_
    extends MyEBean
{

    private Context context_;

    private MyEBean_(Context context) {
        context_ = context;
        init_();
    }

    public static MyEBean_ getInstance_(Context context) {
        return new MyEBean_(context);
    }

    private void init_() {
        afterInject();
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
